import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/assets/theme-provider";
import { SessionProvider } from "next-auth/react"
import { SessionGuard } from "@/components/check/session-guard";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider session={session} refetchInterval={60}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionGuard>
              <main >{children}</main>
              <Toaster position="top-center" />
            </SessionGuard>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
